services:
  lint:
    image: buildkite/plugin-linter
    command: ["--id", "envato/github-pipeline-upload"]
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
