#!/bin/bash

PIPELINE_FILE="${BUILDKITE_PLUGIN_GITHUB_PIPELINE_UPLOAD_FILE:-.buildkite/pipeline.yml}"

echo "~~~ :pipeline: Uploading $PIPELINE_FILE"

if [[ $BUILDKITE_REPO =~ git@github.com:([[a-zA-Z0-9/_-]*)\.git$ ]]; then
  REPO_SLUG=${BASH_REMATCH[1]}
fi

if [ -z "$REPO_SLUG" ]; then
  echo "Failed to extract repository slug from BUILDKITE_REPO"
  exit 1
fi

if [ -z "$GITHUB_ACCESS_TOKEN" ]; then
  echo "Missing required GITHUB_ACCESS_TOKEN"
  exit 1
fi

echo "Using https://api.github.com/repos/${REPO_SLUG}/contents/${PIPELINE_FILE}?ref=${BUILDKITE_BRANCH}"

PIPELINE_CONTENTS=$(curl --silent --fail -H "Authorization: token ${GITHUB_ACCESS_TOKEN}" -H "Accept: application/vnd.github.v3.raw" -L "https://api.github.com/repos/${REPO_SLUG}/contents/${PIPELINE_FILE}?ref=${BUILDKITE_BRANCH}")

if [ -z "$PIPELINE_CONTENTS" ]; then
  echo "Github API Error"
  exit 1
fi

echo "$PIPELINE_CONTENTS" | buildkite-agent pipeline upload
